# Site
repository: goo-mingi/goo-mingi.github.io
favicon: images/IMG_0119.JPG

# Content configuration version
version: 2

# Personal info
name: Mingi GOO (구민기)
title: Data Scientist at Storelink
email: gmg.mingi.goo@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  goo-mingi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: 민기-구-b83061169
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "G-H1BCBS1SXL"

# About Section
# about_title: About Me
about_profile_image: images/IMG_0119.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Mingi Goo. I'm a data scientist from South Korea, currently working at Storelink. I have worked with <mark>R</mark> and <mark>Python</mark>, including SQL, AWS and Github, and utilized Streamlit to serve data analysis applications.

  If you want to understand me formally, you can refer to my <mark>(CV)[https://1drv.ms/b/s!ArR47cH0ml_jjKhEWZHwgokPu995zw?e=Q4ftP8]</mark>.

  One of my unusual hobbies is to study languages: I can speak <mark>English</mark>, <mark>Chinese(Mandarin)</mark>, <mark>Japanese</mark>, as well as my mother tongue <mark>Korean</mark>.



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: STP Planning Project
        Company: Korean Leading Life Insurance Company (Confidential)
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This project aimed to create a totally new STP strategy, bringing focus to consumers' <mark>digital behavior</mark>.
        description: | # this will include new lines to allow paragraphs
          At my time at SNU, I collaborated on this project with 4 professors, including my advisor, and fellow graduate students, from the fields of Marketing, Information Systems and Finance Major. My responsibilities were as follows:

            1) <mark>Developing a comprehensive survey</mark> to understand customers' insurance purchasing journey and their digital behavior
            2) <mark>Analyzing the survey data</mark> to identify latent demand and effectively target potential customers
            3) <mark>Proposing field-specific tactics</mark> for potential customer segments

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Storelink
        link: storelink.io
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: February 2022 - Present
        quote: >
          Storelink is an e-marketing solution company specializing in data-driven marketing strategies. Our customers include conglomerates and SMEs, and we are growing rapidly. 
        description: | # this will include new lines to allow paragraphs
            As a Data Scientist at Storelink, I focus on online marketplaces. Below are some of the market analysis projects I have carried out:

              1) <mark>Brand Involvement Analysis</mark> : While consumers tend to refer to the rank when they purchase in online markets, some products are more influenced by their brands than the rank itself. We call this *Keywords in High Brand Involvement*. This model analyzes whether the products from the result of a keyword have high brand involvement or not. This model has become a *core competence* of my company, and we are now developing it for customers to use this model on our website.


              2) <mark>Customer Segmentation</mark> : We have many customers to buy the products of our business partners. To enhance the success rate of our marketing campaigns, I am developing a *customer segmentation model for targeted marketing*.


              3) <mark>Algorithm Detection<mark> : One of our top priorities is to expose our customers' products at the top of the search result site. Therefore, changes in the search algorithms are crucial to our business. I have identified the key variables that significantly impact search algorithms, as well as the timings of algorithm changes.
              
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul National University (SNU)
        caption: 2021 - 2023
        sub_title: MSc Business Administration (Quantitative Marketing)
        quote: >
          *(Advisor : Prof. Jun B. Kim)* Seoul National University is a top school in South Korea, and one of the leading universities of Asia.
        description: | # this will include new lines to allow paragraphs
          During my time at SNU, I learnt <mark>Quantitative marketing</mark> under many prominent marketing professors, which allows me to solve marketing problems based on data. Especially, I have been interested in <mark>consumer search</mark>, <mark>e-commerce</mark>, <mark>Bayesian statistics</mark> and <mark>machine learning</mark>.

            1) Dissertation : Heterogeneous Rank Effects in Online Marketplaces


            2) Replicates of Rossi, McCulloch and Allenby


            3) Analysis of the Floating Population in commercial districs in Seoul

        

          Featured Courseworks : Special Topics in Quantitative Marketing, Studies in quantitative Marketing Decision Making, Seminars in Marketing Models, Studies in Econometrics
      - layout: left
        title: Kyunghee University (KHU)
        caption: 2015 - 2021
        sub_title: BBA Hospitality Management
        quote: >
          As a leading university in Seoul, KHU's hospitality management is the most well-known major, offering comprehensive education in business administration and the hospitality industry.
        description: |
          At KHU, I learnt various business problems specializing in the hospitality industry. While the major was industry-specific, the methodology I have learnt was generalizable; statistics and business analytics allowed me to pursue an MSc in quantitative marketing. FYI, I was also interested in political science, so I took some courses of Korean politics and international relations.

          I was involved in many student clubs as follows:

          
            - Business Analytics and Consulting Club <mark>Co-founder</mark>
            
              - I was one of the co-founders of this club. We actively find fellows to study business analytics and data analysis to initiate our club.
              - We enthusiastically studied *statistics* and *R*. If we have any unsolved problems, we visit our advisor *Prof. Gyuwan Choi* and his doctoral student.
              - This club was so successful that the number of our alumni already exceeded twenty!
              
            - Service Strategic Management Club <mark>Leader</mark>
            
              - We studied strategic management, both from textbook study and from case study.
              - On every vacation, we carried out projects for service enterprises to apply our knowledge --- I was affiliated with BENIKEA headquarters, which is a hotel cooperative owned by the Korean government.
              - We proposed many marketing strategies to attract more customers, especially focusing on developing its unique style such as Providing traditional amenities and new branding to maintain its brand values.
              
            - Student Council <mark>Leader of PR Team</mark>
            
              - As the leader of the PR team, I was responsible for managing the social media accounts of my major.
              - To notify as many students as possible was my top priority --- I was always considering when to upload, how to upload and what to upload.
              
            - International Friendship and Culture Exchange Club <mark>Member</mark>
            
              - As a multilingual in East Asian languages, I was responsible to take care of many students from Chinese region and Japan.
              - One of my experience in this club includes to deal with an unusual situation involved with police, and the situation was solved easily, fortunately.
              - My best experience during my undergraduate that I could broaden my insights to languages, cultures and people.

          Featured Courseworks related to Quantitative Marketing : Business Analytics, Business Statistics, Principles of Economics, Essentials of Marketing Research, Theory of Marketing
          Featured Courseworks related to Hospitality Management : Hospitality Strategic Management Case Study, Internet Marketing in Hospitality Industry, Hotel Management Analysis and M&A, Hotel Rooms Management
          Featured Courseworks related to Political Science : International Relations Theories and Their Applications, Theories of International Relations, Comparative Politics, Government and Politics of Korea

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs

      I really like to travel all around the world! I want to list all the cities I have ever been to here!

      I've been to:
        - Asia
          - South Korea : Seoul, Busan, Jeju, Gwangju, Gangneung
          - Taiwan : Taipei, Chia'yi, Keelung, Taichung
          - Mainland China : Guangzhou, Xianggelila, Lijiang, Dali, Kunming, Xining
          - Hong Kong
          - Japan : Fukuoka, Osaka, Kyoto
          - Thailand : Bangkok
        - Europe
          - United Kingdom : London, Edinburgh, Brighton, Oxford, Glasgow
          - Italy : Rome, Positano, Florence, Milan, Venice
          - Switzerland : Interlaken
          - Austria : Vienna, Salzburg
          - Hungary : Budapest
          - Czech Republc : Prague
          - Germany : Munich, Berlin, Dresden, Koeln, Frankfurt am Main
          - Belgium : Brussels
          - France : Paris
        - North America
          - the United States : Washington D.C., New York City, Boston
    
        While it may seem like I'm wealthy, the truth is I've worked really hard to fund my travels. If you are interested in my travel stories, you can visit [my blog](https://blog.naver.com/alsrl_1217). Sorry for only Korean.

    
    
      I love <mark>sleeping</mark>, but I also enjoy going to the <mark>gym</mark> and <mark>running</mark>. Additionally, I love perfumes. 

      # Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      # - Rock climbing
      # - Gaming
      # - Knitting
      # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      # Look at this cool image  
      # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
